-- Pending membership invitations. A person is not an organisation member
-- until they accept with the emailed token while signed in as that email.

create table public.organisation_invitations (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null references public.organisations (id) on delete cascade,
    email text not null,
    role text not null,
    token text not null,
    invited_by_email text not null,
    organisation_name text not null,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,
    accepted_at timestamptz,
    constraint organisation_invitations_email_check check (email like '%@%'),
    constraint organisation_invitations_invited_by_check check (invited_by_email like '%@%'),
    constraint organisation_invitations_name_check check (char_length(trim(organisation_name)) > 0),
    constraint organisation_invitations_role_check check (role in ('OWNER', 'ADMIN', 'MEMBER')),
    constraint organisation_invitations_token_check check (char_length(token) = 64),
    constraint organisation_invitations_token_key unique (token)
);

create unique index organisation_invitations_pending_org_email
    on public.organisation_invitations (organisation_id, email)
    where accepted_at is null;

create index organisation_invitations_email_idx
    on public.organisation_invitations (email);

create index organisation_invitations_organisation_id_idx
    on public.organisation_invitations (organisation_id);

alter table public.organisation_invitations enable row level security;

grant select on public.organisation_invitations to authenticated;
revoke insert, update, delete on public.organisation_invitations from anon, authenticated;

drop policy if exists organisation_users_insert on public.organisation_users;

create policy organisation_invitations_select
on public.organisation_invitations
for select
to authenticated
using (
    public.user_organisation_role(organisation_id) in ('OWNER', 'ADMIN')
    or email = public.current_user_email()
);

create function public.organisation_invitations_lowercase_email()
returns trigger
language plpgsql
as $$
begin
    new.email := lower(trim(new.email));
    new.invited_by_email := lower(trim(new.invited_by_email));
    return new;
end;
$$;

create trigger organisation_invitations_lowercase_email
before insert or update of email, invited_by_email on public.organisation_invitations
for each row
execute function public.organisation_invitations_lowercase_email();

create function public.invite_organisation_member(
    p_organisation_id bigint,
    p_email text,
    p_role text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
    v_actor text;
    v_email text;
    v_invitee text;
    v_role text;
    v_name text;
    v_token text;
begin
    v_email := public.current_user_email();
    v_invitee := lower(trim(coalesce(p_email, '')));
    v_role := upper(trim(coalesce(p_role, '')));
    v_actor := public.user_organisation_role(p_organisation_id);

    if v_email is null or v_email = '' then
        raise exception 'Not authenticated';
    end if;

    if v_actor is null or v_actor not in ('OWNER', 'ADMIN') then
        raise exception 'You do not have permission to invite members';
    end if;

    if v_role not in ('OWNER', 'ADMIN', 'MEMBER') then
        raise exception 'Choose a valid role';
    end if;

    if v_actor = 'ADMIN' and v_role not in ('ADMIN', 'MEMBER') then
        raise exception 'You cannot assign that role';
    end if;

    if v_invitee is null or v_invitee not like '%@%' then
        raise exception 'Enter a valid email address';
    end if;

    if v_invitee = v_email then
        raise exception 'You cannot invite yourself';
    end if;

    if exists (
        select 1
        from public.organisation_users
        where organisation_id = p_organisation_id
          and email = v_invitee
    ) then
        raise exception 'That email is already a member of this account';
    end if;

    select legal_name into v_name
    from public.organisations
    where id = p_organisation_id;

    if v_name is null then
        raise exception 'Organisation not found';
    end if;

    v_token := replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');

    delete from public.organisation_invitations
    where organisation_id = p_organisation_id
      and email = v_invitee
      and accepted_at is null;

    insert into public.organisation_invitations (
        organisation_id,
        email,
        role,
        token,
        invited_by_email,
        organisation_name,
        expires_at
    )
    values (
        p_organisation_id,
        v_invitee,
        v_role,
        v_token,
        v_email,
        v_name,
        now() + interval '14 days'
    );

    return v_token;
end;
$$;

revoke all on function public.invite_organisation_member(bigint, text, text) from public;
grant execute on function public.invite_organisation_member(bigint, text, text) to authenticated;

create function public.get_organisation_invitation(p_token text)
returns table (
    id bigint,
    organisation_id bigint,
    organisation_name text,
    email text,
    role text,
    expires_at timestamptz,
    accepted_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
    if public.current_user_email() is null then
        raise exception 'Not authenticated';
    end if;

    return query
    select
        invitation.id,
        invitation.organisation_id,
        invitation.organisation_name,
        invitation.email,
        invitation.role,
        invitation.expires_at,
        invitation.accepted_at
    from public.organisation_invitations as invitation
    where invitation.token = trim(coalesce(p_token, ''));
end;
$$;

revoke all on function public.get_organisation_invitation(text) from public;
grant execute on function public.get_organisation_invitation(text) to authenticated;

create function public.accept_organisation_invitation(p_token text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_email text;
    v_invite public.organisation_invitations%rowtype;
begin
    v_email := public.current_user_email();

    if v_email is null or v_email = '' then
        raise exception 'Not authenticated';
    end if;

    select *
    into v_invite
    from public.organisation_invitations
    where token = trim(coalesce(p_token, ''));

    if not found then
        raise exception 'Invitation not found';
    end if;

    if v_invite.email <> v_email then
        raise exception 'This invitation was sent to a different email';
    end if;

    if v_invite.accepted_at is not null then
        return v_invite.organisation_id;
    end if;

    if v_invite.expires_at <= now() then
        raise exception 'This invitation has expired';
    end if;

    insert into public.organisation_users (organisation_id, email, role)
    values (v_invite.organisation_id, v_email, v_invite.role)
    on conflict (organisation_id, email) do nothing;

    update public.organisation_invitations
    set accepted_at = now()
    where id = v_invite.id
      and accepted_at is null;

    return v_invite.organisation_id;
end;
$$;

revoke all on function public.accept_organisation_invitation(text) from public;
grant execute on function public.accept_organisation_invitation(text) to authenticated;

create function public.decline_organisation_invitation(p_token text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_email text;
    v_deleted integer;
begin
    v_email := public.current_user_email();

    if v_email is null or v_email = '' then
        raise exception 'Not authenticated';
    end if;

    delete from public.organisation_invitations
    where token = trim(coalesce(p_token, ''))
      and email = v_email
      and accepted_at is null;

    get diagnostics v_deleted = row_count;

    if v_deleted = 0 then
        raise exception 'Invitation not found';
    end if;
end;
$$;

revoke all on function public.decline_organisation_invitation(text) from public;
grant execute on function public.decline_organisation_invitation(text) to authenticated;

create function public.cancel_organisation_invitation(p_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_org bigint;
    v_role text;
    v_actor text;
    v_deleted integer;
begin
    if public.current_user_email() is null then
        raise exception 'Not authenticated';
    end if;

    select organisation_id, role
    into v_org, v_role
    from public.organisation_invitations
    where id = p_id
      and accepted_at is null;

    if v_org is null then
        raise exception 'Invitation not found';
    end if;

    v_actor := public.user_organisation_role(v_org);

    if v_actor is null
       or v_actor not in ('OWNER', 'ADMIN')
       or (v_actor = 'ADMIN' and v_role = 'OWNER') then
        raise exception 'You cannot cancel that invitation';
    end if;

    delete from public.organisation_invitations
    where id = p_id
      and accepted_at is null;

    get diagnostics v_deleted = row_count;

    if v_deleted = 0 then
        raise exception 'Invitation not found';
    end if;
end;
$$;

revoke all on function public.cancel_organisation_invitation(bigint) from public;
grant execute on function public.cancel_organisation_invitation(bigint) to authenticated;

create or replace function public.sync_organisation_user_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_old text;
    v_new text;
begin
    if new.email is null
       or old.email is null
       or lower(new.email) is not distinct from lower(old.email) then
        return new;
    end if;

    v_old := lower(old.email);
    v_new := lower(new.email);

    update public.organisation_users
    set email = v_new
    where email = v_old;

    if not exists (
        select 1 from public.user_email_preferences where email = v_new
    ) then
        update public.user_email_preferences
        set email = v_new
        where email = v_old;
    else
        delete from public.user_email_preferences
        where email = v_old;
    end if;

    delete from public.listing_alerts as incoming
    using public.listing_alerts as existing
    where incoming.email = v_old
      and existing.email = v_new
      and incoming.fishery_id = existing.fishery_id;

    update public.listing_alerts
    set email = v_new
    where email = v_old;

    update public.user_notifications
    set email = v_new
    where email = v_old;

    delete from public.terms_acceptances as incoming
    using public.terms_acceptances as existing
    where incoming.email = v_old
      and existing.email = v_new
      and incoming.terms_version = existing.terms_version;

    update public.terms_acceptances
    set email = v_new
    where email = v_old;

    delete from public.organisation_invitations as incoming
    using public.organisation_invitations as existing
    where incoming.email = v_old
      and existing.email = v_new
      and incoming.organisation_id = existing.organisation_id
      and incoming.accepted_at is null
      and existing.accepted_at is null;

    update public.organisation_invitations
    set email = v_new
    where email = v_old;

    return new;
end;
$$;

notify pgrst, 'reload schema';
