-- Phase 7: simulated purchase workflow. No live payments, auctions, or Stripe.

alter table public.listings
    drop constraint listings_status_check;

alter table public.listings
    add constraint listings_status_check
        check (status in (
            'PENDING_APPROVAL',
            'PUBLISHED',
            'RESERVED',
            'SOLD',
            'CANCELLED',
            'REJECTED'
        ));

create table public.orders (
    id bigint generated by default as identity primary key,
    listing_id bigint not null references public.listings (id) on delete restrict,
    holding_id bigint not null references public.quota_holdings (id) on delete restrict,
    seller_organisation_id bigint not null references public.organisations (id) on delete restrict,
    buyer_organisation_id bigint not null references public.organisations (id) on delete restrict,
    offering text not null,
    quantity numeric(18, 6) not null,
    unit_price_aud numeric(18, 2) not null,
    amount_aud numeric(18, 2) not null,
    status text not null,
    seller_name text not null,
    buyer_name text not null,
    fishery_name text not null,
    stock_name text not null,
    season_name text not null,
    quota_type_name text not null,
    measurement_kind text not null,
    unit_label text not null,
    created_by_email text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    review_note text,
    constraint orders_offering_check check (offering in ('SALE', 'LEASE')),
    constraint orders_status_check
        check (status in (
            'AWAITING_COMPLIANCE',
            'AWAITING_TRANSFER',
            'AWAITING_SETTLEMENT',
            'COMPLETED',
            'REJECTED',
            'CANCELLED'
        )),
    constraint orders_quantity_check check (quantity > 0),
    constraint orders_price_check check (unit_price_aud > 0),
    constraint orders_amount_check check (amount_aud > 0),
    constraint orders_buyer_seller_check
        check (buyer_organisation_id <> seller_organisation_id)
);

create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

create unique index orders_one_open_listing_idx
    on public.orders (listing_id)
    where status not in ('REJECTED', 'CANCELLED');

create index orders_buyer_organisation_id_idx
    on public.orders (buyer_organisation_id);
create index orders_seller_organisation_id_idx
    on public.orders (seller_organisation_id);
create index orders_status_idx
    on public.orders (status);

create table public.quota_reservations (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique references public.orders (id) on delete restrict,
    listing_id bigint not null references public.listings (id) on delete restrict,
    holding_id bigint not null references public.quota_holdings (id) on delete restrict,
    quantity numeric(18, 6) not null,
    status text not null,
    created_at timestamptz not null default now(),
    released_at timestamptz,
    constraint quota_reservations_status_check
        check (status in ('ACTIVE', 'RELEASED', 'CONSUMED')),
    constraint quota_reservations_quantity_check check (quantity > 0)
);

create unique index quota_reservations_one_active_listing_idx
    on public.quota_reservations (listing_id)
    where status = 'ACTIVE';

create index quota_reservations_holding_id_idx
    on public.quota_reservations (holding_id);

create table public.transactions (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique references public.orders (id) on delete restrict,
    status text not null,
    amount_aud numeric(18, 2) not null,
    created_at timestamptz not null default now(),
    completed_at timestamptz,
    constraint transactions_status_check
        check (status in ('PENDING', 'COMPLETED')),
    constraint transactions_amount_check check (amount_aud > 0)
);

create table public.audit_events (
    id bigint generated by default as identity primary key,
    event_type text not null,
    entity_type text not null,
    entity_id bigint not null,
    actor_email text,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index audit_events_entity_idx
    on public.audit_events (entity_type, entity_id);

alter table public.orders enable row level security;
alter table public.quota_reservations enable row level security;
alter table public.transactions enable row level security;
alter table public.audit_events enable row level security;

grant select on public.orders to authenticated;
grant select on public.quota_reservations to authenticated;
grant select on public.transactions to authenticated;
grant select on public.audit_events to authenticated;

create policy orders_select
on public.orders
for select
to authenticated
using (
    public.user_organisation_role(buyer_organisation_id) is not null
    or public.user_organisation_role(seller_organisation_id) is not null
    or public.is_platform_admin()
);

create policy quota_reservations_select
on public.quota_reservations
for select
to authenticated
using (
    exists (
        select 1
        from public.orders as o
        where o.id = quota_reservations.order_id
          and (
              public.user_organisation_role(o.buyer_organisation_id) is not null
              or public.user_organisation_role(o.seller_organisation_id) is not null
              or public.is_platform_admin()
          )
    )
);

create policy transactions_select
on public.transactions
for select
to authenticated
using (
    exists (
        select 1
        from public.orders as o
        where o.id = transactions.order_id
          and (
              public.user_organisation_role(o.buyer_organisation_id) is not null
              or public.user_organisation_role(o.seller_organisation_id) is not null
              or public.is_platform_admin()
          )
    )
);

create policy audit_events_select
on public.audit_events
for select
to authenticated
using (
    public.is_platform_admin()
    or (
        entity_type = 'order'
        and exists (
            select 1
            from public.orders as o
            where o.id = audit_events.entity_id
              and (
                  public.user_organisation_role(o.buyer_organisation_id) is not null
                  or public.user_organisation_role(o.seller_organisation_id) is not null
              )
        )
    )
);

create policy listings_buyer_select
on public.listings
for select
to authenticated
using (
    exists (
        select 1
        from public.orders as o
        where o.listing_id = listings.id
          and public.user_organisation_role(o.buyer_organisation_id) is not null
    )
);

create function public.write_audit_event(
    p_event_type text,
    p_entity_type text,
    p_entity_id bigint,
    p_payload jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.audit_events (
        event_type,
        entity_type,
        entity_id,
        actor_email,
        payload
    )
    values (
        p_event_type,
        p_entity_type,
        p_entity_id,
        public.current_user_email(),
        coalesce(p_payload, '{}'::jsonb)
    );
end;
$$;

revoke all on function public.write_audit_event(text, text, bigint, jsonb) from public;

create function public.apply_quota_event(
    p_holding_id bigint,
    p_event_type text,
    p_quantity_delta numeric,
    p_note text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_holding public.quota_holdings%rowtype;
    v_after numeric;
begin
    select * into v_holding
    from public.quota_holdings
    where id = p_holding_id
    for update;

    if not found then
        raise exception 'Holding not found';
    end if;

    v_after := v_holding.quantity + p_quantity_delta;

    if v_after < 0 then
        raise exception 'Quota ledger would be inconsistent';
    end if;

    update public.quota_holdings
    set quantity = v_after
    where id = p_holding_id;

    insert into public.quota_ledger (
        holding_id,
        event_type,
        quantity_delta,
        quantity_after,
        note,
        created_by_email
    )
    values (
        p_holding_id,
        p_event_type,
        p_quantity_delta,
        v_after,
        nullif(trim(p_note), ''),
        public.current_user_email()
    );
end;
$$;

revoke all on function public.apply_quota_event(bigint, text, numeric, text) from public;

create function public.release_order_reservation(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_listing_id bigint;
begin
    update public.quota_reservations
    set
        status = 'RELEASED',
        released_at = now()
    where order_id = p_order_id
      and status = 'ACTIVE'
    returning listing_id into v_listing_id;

    if v_listing_id is null then
        return;
    end if;

    update public.listings
    set status = case
        when expires_at > now() then 'PUBLISHED'
        else 'CANCELLED'
    end
    where id = v_listing_id
      and status = 'RESERVED';
end;
$$;

revoke all on function public.release_order_reservation(bigint) from public;

create or replace function public.create_listing(
    p_holding_id bigint,
    p_offering text,
    p_quantity numeric,
    p_unit_price_aud numeric,
    p_expires_at timestamptz
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_holding public.quota_holdings%rowtype;
    v_role text;
    v_id bigint;
    v_seller text;
    v_fishery text;
    v_stock text;
    v_season text;
    v_quota_type text;
    v_kind text;
    v_unit text;
    v_committed numeric;
begin
    if public.current_user_email() is null then
        raise exception 'Not authenticated';
    end if;

    select * into v_holding
    from public.quota_holdings
    where id = p_holding_id
    for update;

    if not found then
        raise exception 'Holding not found';
    end if;

    v_role := public.user_organisation_role(v_holding.organisation_id);

    if v_role is null or v_role not in ('OWNER', 'ADMIN') then
        raise exception 'You cannot list quota for this organisation';
    end if;

    if p_offering not in ('SALE', 'LEASE') then
        raise exception 'Offering must be SALE or LEASE';
    end if;

    if p_quantity is null or p_quantity <= 0 then
        raise exception 'Quantity must be greater than zero';
    end if;

    v_committed := coalesce((
        select sum(r.quantity)
        from public.quota_reservations as r
        where r.holding_id = p_holding_id
          and r.status = 'ACTIVE'
    ), 0) + coalesce((
        select sum(l.quantity)
        from public.listings as l
        where l.holding_id = p_holding_id
          and l.status in ('PENDING_APPROVAL', 'PUBLISHED')
    ), 0);

    if p_quantity > v_holding.quantity - v_committed then
        raise exception 'Quantity cannot exceed the available holding';
    end if;

    if p_unit_price_aud is null or p_unit_price_aud <= 0 then
        raise exception 'Price must be greater than zero';
    end if;

    if p_expires_at is null or p_expires_at <= now() then
        raise exception 'Expiry must be in the future';
    end if;

    select o.legal_name into v_seller
    from public.organisations as o
    where o.id = v_holding.organisation_id;

    select f.name, st.name, se.name, qt.name, qt.measurement_kind, qt.unit_label
    into v_fishery, v_stock, v_season, v_quota_type, v_kind, v_unit
    from public.stocks as st
    join public.fisheries as f on f.id = st.fishery_id
    join public.seasons as se on se.id = v_holding.season_id
    join public.quota_types as qt on qt.id = v_holding.quota_type_id
    where st.id = v_holding.stock_id;

    insert into public.listings (
        organisation_id,
        holding_id,
        listing_type,
        offering,
        quantity,
        unit_price_aud,
        expires_at,
        status,
        seller_name,
        fishery_name,
        stock_name,
        season_name,
        quota_type_name,
        measurement_kind,
        unit_label,
        created_by_email
    )
    values (
        v_holding.organisation_id,
        p_holding_id,
        'FIXED_PRICE',
        p_offering,
        p_quantity,
        p_unit_price_aud,
        p_expires_at,
        'PENDING_APPROVAL',
        v_seller,
        v_fishery,
        v_stock,
        v_season,
        v_quota_type,
        v_kind,
        v_unit,
        public.current_user_email()
    )
    returning id into v_id;

    return v_id;
end;
$$;

create function public.create_order(
    p_listing_id bigint,
    p_buyer_organisation_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_listing public.listings%rowtype;
    v_holding public.quota_holdings%rowtype;
    v_buyer_name text;
    v_available numeric;
    v_amount numeric;
    v_order_id bigint;
begin
    if public.current_user_email() is null then
        raise exception 'Not authenticated';
    end if;

    if public.user_organisation_role(p_buyer_organisation_id) is null then
        raise exception 'You are not a member of that organisation';
    end if;

    select * into v_listing
    from public.listings
    where id = p_listing_id
    for update;

    if not found then
        raise exception 'Listing not found';
    end if;

    if v_listing.status <> 'PUBLISHED' or v_listing.expires_at <= now() then
        raise exception 'Listing is not available to purchase';
    end if;

    if p_buyer_organisation_id = v_listing.organisation_id then
        raise exception 'You cannot purchase your organisation''s listing';
    end if;

    select legal_name into v_buyer_name
    from public.organisations
    where id = p_buyer_organisation_id;

    if v_buyer_name is null then
        raise exception 'Organisation not found';
    end if;

    select * into v_holding
    from public.quota_holdings
    where id = v_listing.holding_id
    for update;

    if not found then
        raise exception 'Holding not found';
    end if;

    v_available := v_holding.quantity - coalesce((
        select sum(r.quantity)
        from public.quota_reservations as r
        where r.holding_id = v_holding.id
          and r.status = 'ACTIVE'
    ), 0);

    if v_listing.quantity > v_available then
        raise exception 'Quota is no longer available';
    end if;

    v_amount := round(v_listing.quantity * v_listing.unit_price_aud, 2);

    if v_amount is null or v_amount <= 0 then
        raise exception 'Order amount must be greater than zero';
    end if;

    insert into public.orders (
        listing_id,
        holding_id,
        seller_organisation_id,
        buyer_organisation_id,
        offering,
        quantity,
        unit_price_aud,
        amount_aud,
        status,
        seller_name,
        buyer_name,
        fishery_name,
        stock_name,
        season_name,
        quota_type_name,
        measurement_kind,
        unit_label,
        created_by_email
    )
    values (
        v_listing.id,
        v_listing.holding_id,
        v_listing.organisation_id,
        p_buyer_organisation_id,
        v_listing.offering,
        v_listing.quantity,
        v_listing.unit_price_aud,
        v_amount,
        'AWAITING_COMPLIANCE',
        v_listing.seller_name,
        v_buyer_name,
        v_listing.fishery_name,
        v_listing.stock_name,
        v_listing.season_name,
        v_listing.quota_type_name,
        v_listing.measurement_kind,
        v_listing.unit_label,
        public.current_user_email()
    )
    returning id into v_order_id;

    insert into public.quota_reservations (
        order_id,
        listing_id,
        holding_id,
        quantity,
        status
    )
    values (
        v_order_id,
        v_listing.id,
        v_listing.holding_id,
        v_listing.quantity,
        'ACTIVE'
    );

    insert into public.transactions (
        order_id,
        status,
        amount_aud
    )
    values (
        v_order_id,
        'PENDING',
        v_amount
    );

    update public.listings
    set status = 'RESERVED'
    where id = v_listing.id;

    perform public.write_audit_event(
        'ORDER_CREATED',
        'order',
        v_order_id,
        jsonb_build_object(
            'listing_id', v_listing.id,
            'quantity', v_listing.quantity
        )
    );

    perform public.write_audit_event(
        'QUOTA_RESERVED',
        'order',
        v_order_id,
        jsonb_build_object(
            'holding_id', v_listing.holding_id,
            'quantity', v_listing.quantity
        )
    );

    return v_order_id;
end;
$$;

revoke all on function public.create_order(bigint, bigint) from public;
grant execute on function public.create_order(bigint, bigint) to authenticated;

create function public.cancel_order(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_order public.orders%rowtype;
begin
    select * into v_order
    from public.orders
    where id = p_order_id
    for update;

    if not found then
        raise exception 'Order not found';
    end if;

    if v_order.status <> 'AWAITING_COMPLIANCE' then
        raise exception 'Order cannot be cancelled';
    end if;

    if not public.is_platform_admin()
       and public.user_organisation_role(v_order.buyer_organisation_id) is null then
        raise exception 'You cannot cancel this order';
    end if;

    update public.orders
    set status = 'CANCELLED'
    where id = p_order_id;

    perform public.release_order_reservation(p_order_id);

    perform public.write_audit_event(
        'ORDER_CANCELLED',
        'order',
        p_order_id,
        '{}'::jsonb
    );
end;
$$;

revoke all on function public.cancel_order(bigint) from public;
grant execute on function public.cancel_order(bigint) to authenticated;

create function public.approve_compliance(p_order_id bigint, p_note text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_platform_admin() then
        raise exception 'Not a platform admin';
    end if;

    update public.orders
    set
        status = 'AWAITING_TRANSFER',
        review_note = nullif(trim(p_note), '')
    where id = p_order_id
      and status = 'AWAITING_COMPLIANCE';

    if not found then
        raise exception 'Order is not waiting for compliance review';
    end if;

    perform public.write_audit_event(
        'COMPLIANCE_APPROVED',
        'order',
        p_order_id,
        jsonb_build_object('note', nullif(trim(p_note), ''))
    );
end;
$$;

revoke all on function public.approve_compliance(bigint, text) from public;
grant execute on function public.approve_compliance(bigint, text) to authenticated;

create function public.reject_compliance(p_order_id bigint, p_note text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_platform_admin() then
        raise exception 'Not a platform admin';
    end if;

    update public.orders
    set
        status = 'REJECTED',
        review_note = nullif(trim(p_note), '')
    where id = p_order_id
      and status = 'AWAITING_COMPLIANCE';

    if not found then
        raise exception 'Order is not waiting for compliance review';
    end if;

    perform public.release_order_reservation(p_order_id);

    perform public.write_audit_event(
        'COMPLIANCE_REJECTED',
        'order',
        p_order_id,
        jsonb_build_object('note', nullif(trim(p_note), ''))
    );
end;
$$;

revoke all on function public.reject_compliance(bigint, text) from public;
grant execute on function public.reject_compliance(bigint, text) to authenticated;

create function public.simulate_transfer(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_platform_admin() then
        raise exception 'Not a platform admin';
    end if;

    update public.orders
    set status = 'AWAITING_SETTLEMENT'
    where id = p_order_id
      and status = 'AWAITING_TRANSFER';

    if not found then
        raise exception 'Order is not waiting for transfer';
    end if;

    perform public.write_audit_event(
        'TRANSFER_SIMULATED',
        'order',
        p_order_id,
        '{}'::jsonb
    );
end;
$$;

revoke all on function public.simulate_transfer(bigint) from public;
grant execute on function public.simulate_transfer(bigint) to authenticated;

create function public.simulate_settlement(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_order public.orders%rowtype;
    v_listing public.listings%rowtype;
    v_seller_holding public.quota_holdings%rowtype;
    v_buyer_holding public.quota_holdings%rowtype;
    v_reservation public.quota_reservations%rowtype;
    v_seller_event text;
    v_buyer_event text;
    v_note text;
begin
    if not public.is_platform_admin() then
        raise exception 'Not a platform admin';
    end if;

    select * into v_order
    from public.orders
    where id = p_order_id
    for update;

    if not found then
        raise exception 'Order not found';
    end if;

    if v_order.status <> 'AWAITING_SETTLEMENT' then
        raise exception 'Order is not waiting for settlement';
    end if;

    select * into v_listing
    from public.listings
    where id = v_order.listing_id
    for update;

    if v_listing.status <> 'RESERVED' then
        raise exception 'Listing is not reserved';
    end if;

    select * into v_reservation
    from public.quota_reservations
    where order_id = p_order_id
    for update;

    if v_reservation.status <> 'ACTIVE' then
        raise exception 'Quota reservation is not active';
    end if;

    select * into v_seller_holding
    from public.quota_holdings
    where id = v_order.holding_id
    for update;

    if v_order.offering = 'LEASE' then
        v_seller_event := 'LEASE_OUT';
        v_buyer_event := 'LEASE_IN';
    else
        v_seller_event := 'SALE';
        v_buyer_event := 'PURCHASE';
    end if;

    v_note := 'Order ' || p_order_id::text;

    perform public.apply_quota_event(
        v_seller_holding.id,
        v_seller_event,
        -v_order.quantity,
        v_note
    );

    select * into v_buyer_holding
    from public.quota_holdings
    where organisation_id = v_order.buyer_organisation_id
      and stock_id = v_seller_holding.stock_id
      and season_id = v_seller_holding.season_id
      and quota_type_id = v_seller_holding.quota_type_id
    for update;

    if not found then
        begin
            insert into public.quota_holdings (
                organisation_id,
                stock_id,
                season_id,
                quota_type_id,
                quantity
            )
            values (
                v_order.buyer_organisation_id,
                v_seller_holding.stock_id,
                v_seller_holding.season_id,
                v_seller_holding.quota_type_id,
                0
            )
            returning * into v_buyer_holding;
        exception
            when unique_violation then
                select * into v_buyer_holding
                from public.quota_holdings
                where organisation_id = v_order.buyer_organisation_id
                  and stock_id = v_seller_holding.stock_id
                  and season_id = v_seller_holding.season_id
                  and quota_type_id = v_seller_holding.quota_type_id
                for update;
        end;
    end if;

    perform public.apply_quota_event(
        v_buyer_holding.id,
        v_buyer_event,
        v_order.quantity,
        v_note
    );

    update public.quota_reservations
    set
        status = 'CONSUMED',
        released_at = now()
    where id = v_reservation.id
      and status = 'ACTIVE';

    update public.listings
    set status = 'SOLD'
    where id = v_listing.id
      and status = 'RESERVED';

    update public.orders
    set status = 'COMPLETED'
    where id = p_order_id;

    update public.transactions
    set
        status = 'COMPLETED',
        completed_at = now()
    where order_id = p_order_id
      and status = 'PENDING';

    perform public.write_audit_event(
        'SETTLEMENT_SIMULATED',
        'order',
        p_order_id,
        jsonb_build_object(
            'seller_holding_id', v_seller_holding.id,
            'buyer_holding_id', v_buyer_holding.id
        )
    );
end;
$$;

revoke all on function public.simulate_settlement(bigint) from public;
grant execute on function public.simulate_settlement(bigint) to authenticated;
