-- In-app notices plus per-user opt-outs, independent of email.

alter table public.user_email_preferences
    add column disabled_in_app text[] not null default '{}';

create table public.user_notifications (
    id bigint generated by default as identity primary key,
    email text not null,
    template text not null,
    title text not null,
    body text not null default '',
    href text not null default '/dashboard/notifications',
    read_at timestamptz,
    created_at timestamptz not null default now()
);

create index user_notifications_email_created_idx
    on public.user_notifications (email, created_at desc);

create index user_notifications_email_unread_idx
    on public.user_notifications (email)
    where read_at is null;

alter table public.user_notifications enable row level security;

grant select on public.user_notifications to authenticated;

create policy user_notifications_select
on public.user_notifications
for select
to authenticated
using (email = public.current_user_email());

drop function if exists public.update_user_email_preferences(text[]);

create function public.update_user_email_preferences(
    p_disabled_emails text[],
    p_disabled_in_app text[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_email text;
begin
    v_email := public.current_user_email();

    if v_email is null or v_email = '' then
        raise exception 'Not authenticated';
    end if;

    insert into public.user_email_preferences (
        email,
        disabled_emails,
        disabled_in_app
    )
    values (
        v_email,
        coalesce(p_disabled_emails, '{}'),
        coalesce(p_disabled_in_app, '{}')
    )
    on conflict (email) do update
        set disabled_emails = excluded.disabled_emails,
            disabled_in_app = excluded.disabled_in_app;
end;
$$;

revoke all on function public.update_user_email_preferences(text[], text[]) from public;
grant execute on function public.update_user_email_preferences(text[], text[]) to authenticated;

create function public.insert_user_notification(
    p_email text,
    p_template text,
    p_title text,
    p_body text,
    p_href text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_email text;
begin
    v_email := lower(trim(coalesce(p_email, '')));

    if v_email not like '%@%'
       or coalesce(p_template, '') = ''
       or coalesce(p_title, '') = '' then
        return;
    end if;

    insert into public.user_notifications (
        email,
        template,
        title,
        body,
        href
    )
    values (
        v_email,
        p_template,
        p_title,
        coalesce(p_body, ''),
        case
            when coalesce(p_href, '') like '/%' and p_href not like '//%' then p_href
            else '/dashboard/notifications'
        end
    );
end;
$$;

revoke all on function public.insert_user_notification(text, text, text, text, text) from public;
grant execute on function public.insert_user_notification(text, text, text, text, text)
    to authenticated, service_role;

create function public.mark_user_notifications_read(p_ids bigint[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_email text;
begin
    v_email := public.current_user_email();

    if v_email is null or v_email = '' then
        raise exception 'Not authenticated';
    end if;

    update public.user_notifications
    set read_at = now()
    where email = v_email
      and read_at is null
      and (p_ids is null or id = any(p_ids));
end;
$$;

revoke all on function public.mark_user_notifications_read(bigint[]) from public;
grant execute on function public.mark_user_notifications_read(bigint[]) to authenticated;

create or replace function public.sync_organisation_user_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_old text;
    v_new text;
begin
    if new.email is null
       or old.email is null
       or lower(new.email) is not distinct from lower(old.email) then
        return new;
    end if;

    v_old := lower(old.email);
    v_new := lower(new.email);

    update public.organisation_users
    set email = v_new
    where email = v_old;

    if not exists (
        select 1 from public.user_email_preferences where email = v_new
    ) then
        update public.user_email_preferences
        set email = v_new
        where email = v_old;
    else
        delete from public.user_email_preferences
        where email = v_old;
    end if;

    delete from public.listing_alerts as incoming
    using public.listing_alerts as existing
    where incoming.email = v_old
      and existing.email = v_new
      and incoming.fishery_id = existing.fishery_id;

    update public.listing_alerts
    set email = v_new
    where email = v_old;

    update public.user_notifications
    set email = v_new
    where email = v_old;

    return new;
end;
$$;

notify pgrst, 'reload schema';
