-- Phase 6: fixed-price listings. No auctions, payments, or quota reservation.

create table public.listings (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null references public.organisations (id) on delete restrict,
    holding_id bigint not null references public.quota_holdings (id) on delete restrict,
    listing_type text not null default 'FIXED_PRICE',
    offering text not null,
    quantity numeric(18, 6) not null,
    unit_price_aud numeric(18, 2) not null,
    expires_at timestamptz not null,
    status text not null,
    seller_name text not null,
    fishery_name text not null,
    stock_name text not null,
    season_name text not null,
    quota_type_name text not null,
    measurement_kind text not null,
    unit_label text not null,
    created_by_email text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    reviewed_by_email text,
    reviewed_at timestamptz,
    review_note text,
    constraint listings_type_check check (listing_type = 'FIXED_PRICE'),
    constraint listings_offering_check check (offering in ('SALE', 'LEASE')),
    constraint listings_status_check
        check (status in ('PENDING_APPROVAL', 'PUBLISHED', 'CANCELLED', 'REJECTED')),
    constraint listings_quantity_check check (quantity > 0),
    constraint listings_price_check check (unit_price_aud > 0)
);

create trigger listings_set_updated_at
before update on public.listings
for each row
execute function public.set_updated_at();

create index listings_status_expires_idx
    on public.listings (status, expires_at);
create index listings_organisation_id_idx
    on public.listings (organisation_id);

alter table public.listings enable row level security;

grant select on public.listings to anon, authenticated;

create policy listings_public_select
on public.listings
for select
to anon, authenticated
using (
    status = 'PUBLISHED'
    and expires_at > now()
);

create policy listings_member_select
on public.listings
for select
to authenticated
using (public.user_organisation_role(organisation_id) is not null);

create policy listings_admin_select
on public.listings
for select
to authenticated
using (public.is_platform_admin());

create function public.create_listing(
    p_holding_id bigint,
    p_offering text,
    p_quantity numeric,
    p_unit_price_aud numeric,
    p_expires_at timestamptz
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_holding public.quota_holdings%rowtype;
    v_role text;
    v_id bigint;
    v_seller text;
    v_fishery text;
    v_stock text;
    v_season text;
    v_quota_type text;
    v_kind text;
    v_unit text;
begin
    if public.current_user_email() is null then
        raise exception 'Not authenticated';
    end if;

    select * into v_holding
    from public.quota_holdings
    where id = p_holding_id;

    if not found then
        raise exception 'Holding not found';
    end if;

    v_role := public.user_organisation_role(v_holding.organisation_id);

    if v_role is null or v_role not in ('OWNER', 'ADMIN') then
        raise exception 'You cannot list quota for this organisation';
    end if;

    if p_offering not in ('SALE', 'LEASE') then
        raise exception 'Offering must be SALE or LEASE';
    end if;

    if p_quantity is null or p_quantity <= 0 then
        raise exception 'Quantity must be greater than zero';
    end if;

    if p_quantity > v_holding.quantity then
        raise exception 'Quantity cannot exceed the holding';
    end if;

    if p_unit_price_aud is null or p_unit_price_aud <= 0 then
        raise exception 'Price must be greater than zero';
    end if;

    if p_expires_at is null or p_expires_at <= now() then
        raise exception 'Expiry must be in the future';
    end if;

    select o.legal_name into v_seller
    from public.organisations as o
    where o.id = v_holding.organisation_id;

    select f.name, st.name, se.name, qt.name, qt.measurement_kind, qt.unit_label
    into v_fishery, v_stock, v_season, v_quota_type, v_kind, v_unit
    from public.stocks as st
    join public.fisheries as f on f.id = st.fishery_id
    join public.seasons as se on se.id = v_holding.season_id
    join public.quota_types as qt on qt.id = v_holding.quota_type_id
    where st.id = v_holding.stock_id;

    insert into public.listings (
        organisation_id,
        holding_id,
        listing_type,
        offering,
        quantity,
        unit_price_aud,
        expires_at,
        status,
        seller_name,
        fishery_name,
        stock_name,
        season_name,
        quota_type_name,
        measurement_kind,
        unit_label,
        created_by_email
    )
    values (
        v_holding.organisation_id,
        p_holding_id,
        'FIXED_PRICE',
        p_offering,
        p_quantity,
        p_unit_price_aud,
        p_expires_at,
        'PENDING_APPROVAL',
        v_seller,
        v_fishery,
        v_stock,
        v_season,
        v_quota_type,
        v_kind,
        v_unit,
        public.current_user_email()
    )
    returning id into v_id;

    return v_id;
end;
$$;

revoke all on function public.create_listing(bigint, text, numeric, numeric, timestamptz) from public;
grant execute on function public.create_listing(bigint, text, numeric, numeric, timestamptz) to authenticated;

create function public.approve_listing(p_listing_id bigint, p_note text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_platform_admin() then
        raise exception 'Not a platform admin';
    end if;

    update public.listings
    set
        status = 'PUBLISHED',
        reviewed_by_email = public.current_user_email(),
        reviewed_at = now(),
        review_note = nullif(trim(p_note), '')
    where id = p_listing_id
      and status = 'PENDING_APPROVAL';

    if not found then
        raise exception 'Listing is not waiting for approval';
    end if;
end;
$$;

revoke all on function public.approve_listing(bigint, text) from public;
grant execute on function public.approve_listing(bigint, text) to authenticated;

create function public.reject_listing(p_listing_id bigint, p_note text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_platform_admin() then
        raise exception 'Not a platform admin';
    end if;

    update public.listings
    set
        status = 'REJECTED',
        reviewed_by_email = public.current_user_email(),
        reviewed_at = now(),
        review_note = nullif(trim(p_note), '')
    where id = p_listing_id
      and status = 'PENDING_APPROVAL';

    if not found then
        raise exception 'Listing is not waiting for approval';
    end if;
end;
$$;

revoke all on function public.reject_listing(bigint, text) from public;
grant execute on function public.reject_listing(bigint, text) to authenticated;

create function public.cancel_listing(p_listing_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_org bigint;
    v_status text;
    v_role text;
begin
    select organisation_id, status
    into v_org, v_status
    from public.listings
    where id = p_listing_id;

    if not found then
        raise exception 'Listing not found';
    end if;

    if v_status not in ('PENDING_APPROVAL', 'PUBLISHED') then
        raise exception 'Listing cannot be cancelled';
    end if;

    v_role := public.user_organisation_role(v_org);

    if not public.is_platform_admin()
       and (v_role is null or v_role not in ('OWNER', 'ADMIN')) then
        raise exception 'You cannot cancel this listing';
    end if;

    update public.listings
    set status = 'CANCELLED'
    where id = p_listing_id;
end;
$$;

revoke all on function public.cancel_listing(bigint) from public;
grant execute on function public.cancel_listing(bigint) to authenticated;
