-- Phase 9: Stripe Connect test payments. Buyers pay the platform.
-- Sellers receive a destination transfer. No live payouts.

alter table public.organisations
    add column stripe_account_id text,
    add column stripe_charges_enabled boolean not null default false,
    add column stripe_payouts_enabled boolean not null default false,
    add column stripe_details_submitted boolean not null default false;

alter table public.organisations
    add constraint organisations_stripe_account_id_unique
        unique (stripe_account_id);

create function public.protect_organisation_stripe_columns()
returns trigger
language plpgsql
as $$
begin
    if current_user in ('authenticated', 'anon')
       and (
           new.stripe_account_id is distinct from old.stripe_account_id
           or new.stripe_charges_enabled is distinct from old.stripe_charges_enabled
           or new.stripe_payouts_enabled is distinct from old.stripe_payouts_enabled
           or new.stripe_details_submitted is distinct from old.stripe_details_submitted
       ) then
        raise exception 'Stripe status is set by the payment webhook';
    end if;

    return new;
end;
$$;

create trigger organisations_protect_stripe_columns
before update on public.organisations
for each row
execute function public.protect_organisation_stripe_columns();

alter table public.orders
    drop constraint orders_status_check;

alter table public.orders
    add constraint orders_status_check
        check (status in (
            'AWAITING_PAYMENT',
            'AWAITING_COMPLIANCE',
            'AWAITING_TRANSFER',
            'AWAITING_SETTLEMENT',
            'COMPLETED',
            'REJECTED',
            'CANCELLED'
        ));

create table public.payments (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique references public.orders (id) on delete restrict,
    provider text not null default 'stripe',
    checkout_session_id text unique,
    payment_intent_id text,
    status text not null,
    amount_aud numeric(18, 2) not null,
    fee_amount_aud numeric(18, 2) not null default 0,
    currency text not null default 'aud',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint payments_provider_check check (provider = 'stripe'),
    constraint payments_status_check
        check (status in ('PENDING', 'PAID', 'FAILED', 'EXPIRED')),
    constraint payments_amount_check check (amount_aud > 0),
    constraint payments_fee_check check (fee_amount_aud >= 0)
);

create trigger payments_set_updated_at
before update on public.payments
for each row
execute function public.set_updated_at();

create table public.stripe_webhook_events (
    event_id text primary key,
    event_type text not null,
    processed_at timestamptz not null default now()
);

alter table public.payments enable row level security;
alter table public.stripe_webhook_events enable row level security;

grant select on public.payments to authenticated;

create policy payments_select
on public.payments
for select
to authenticated
using (
    public.is_platform_admin()
    or exists (
        select 1
        from public.orders as orders
        where orders.id = payments.order_id
          and (
              public.user_organisation_role(orders.buyer_organisation_id) is not null
              or public.user_organisation_role(orders.seller_organisation_id) is not null
          )
    )
);

create function public.organisation_accepts_card_payments(p_organisation_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(
        (
            select organisations.stripe_charges_enabled
            from public.organisations as organisations
            where organisations.id = p_organisation_id
              and organisations.stripe_account_id is not null
        ),
        false
    )
$$;

revoke all on function public.organisation_accepts_card_payments(bigint) from public;
grant execute on function public.organisation_accepts_card_payments(bigint) to authenticated;

create function public.order_seller_payment_account(p_order_id bigint)
returns table (
    account_id text,
    charges_enabled boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v_order public.orders%rowtype;
begin
    select * into v_order
    from public.orders
    where id = p_order_id;

    if not found then
        return;
    end if;

    if public.user_organisation_role(v_order.buyer_organisation_id) is null
       and not public.is_platform_admin() then
        return;
    end if;

    return query
    select
        organisations.stripe_account_id,
        organisations.stripe_charges_enabled
    from public.organisations as organisations
    where organisations.id = v_order.seller_organisation_id;
end;
$$;

revoke all on function public.order_seller_payment_account(bigint) from public;
grant execute on function public.order_seller_payment_account(bigint) to authenticated;

create function public.attach_organisation_stripe_account(
    p_organisation_id bigint,
    p_account_id text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text;
    v_existing text;
begin
    v_role := public.user_organisation_role(p_organisation_id);

    if v_role is null or v_role not in ('OWNER', 'ADMIN') then
        raise exception 'You cannot connect payments for that account';
    end if;

    if p_account_id is null or length(trim(p_account_id)) = 0 then
        raise exception 'Stripe account is required';
    end if;

    select stripe_account_id
    into v_existing
    from public.organisations
    where id = p_organisation_id
    for update;

    if not found then
        raise exception 'Organisation not found';
    end if;

    if v_existing is not null and v_existing <> trim(p_account_id) then
        raise exception 'This account is already connected to Stripe';
    end if;

    update public.organisations
    set stripe_account_id = trim(p_account_id)
    where id = p_organisation_id;
end;
$$;

revoke all on function public.attach_organisation_stripe_account(bigint, text) from public;
grant execute on function public.attach_organisation_stripe_account(bigint, text) to authenticated;

create function public.sync_organisation_stripe_status(
    p_account_id text,
    p_charges_enabled boolean,
    p_payouts_enabled boolean,
    p_details_submitted boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.organisations
    set
        stripe_charges_enabled = coalesce(p_charges_enabled, false),
        stripe_payouts_enabled = coalesce(p_payouts_enabled, false),
        stripe_details_submitted = coalesce(p_details_submitted, false)
    where stripe_account_id = trim(p_account_id);

    if not found then
        return;
    end if;
end;
$$;

revoke all on function public.sync_organisation_stripe_status(text, boolean, boolean, boolean) from public;
grant execute on function public.sync_organisation_stripe_status(text, boolean, boolean, boolean) to service_role;

create function public.upsert_order_payment(
    p_order_id bigint,
    p_checkout_session_id text,
    p_payment_intent_id text,
    p_amount_aud numeric,
    p_fee_amount_aud numeric
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_order public.orders%rowtype;
begin
    select * into v_order
    from public.orders
    where id = p_order_id
    for update;

    if not found then
        raise exception 'Order not found';
    end if;

    if v_order.status <> 'AWAITING_PAYMENT' then
        raise exception 'Order is not waiting for payment';
    end if;

    if public.user_organisation_role(v_order.buyer_organisation_id) is null
       and not public.is_platform_admin() then
        raise exception 'You cannot pay this order';
    end if;

    insert into public.payments (
        order_id,
        checkout_session_id,
        payment_intent_id,
        status,
        amount_aud,
        fee_amount_aud
    )
    values (
        p_order_id,
        nullif(trim(p_checkout_session_id), ''),
        nullif(trim(p_payment_intent_id), ''),
        'PENDING',
        p_amount_aud,
        coalesce(p_fee_amount_aud, 0)
    )
    on conflict (order_id) do update
    set
        checkout_session_id = excluded.checkout_session_id,
        payment_intent_id = coalesce(
            excluded.payment_intent_id,
            public.payments.payment_intent_id
        ),
        status = 'PENDING',
        amount_aud = excluded.amount_aud,
        fee_amount_aud = excluded.fee_amount_aud
    where public.payments.status <> 'PAID';
end;
$$;

revoke all on function public.upsert_order_payment(bigint, text, text, numeric, numeric) from public;
grant execute on function public.upsert_order_payment(bigint, text, text, numeric, numeric) to authenticated;

create function public.record_stripe_webhook_event(
    p_event_id text,
    p_event_type text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    v_event_id text;
begin
    insert into public.stripe_webhook_events (event_id, event_type)
    values (trim(p_event_id), trim(p_event_type))
    on conflict (event_id) do nothing
    returning event_id into v_event_id;

    return v_event_id is not null;
end;
$$;

revoke all on function public.record_stripe_webhook_event(text, text) from public;
grant execute on function public.record_stripe_webhook_event(text, text) to service_role;

create function public.mark_order_paid(
    p_order_id bigint,
    p_checkout_session_id text,
    p_payment_intent_id text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_order public.orders%rowtype;
begin
    select * into v_order
    from public.orders
    where id = p_order_id
    for update;

    if not found then
        raise exception 'Order not found';
    end if;

    if v_order.status = 'AWAITING_COMPLIANCE'
       and exists (
           select 1
           from public.payments
           where order_id = p_order_id
             and status = 'PAID'
       ) then
        return;
    end if;

    if v_order.status <> 'AWAITING_PAYMENT' then
        raise exception 'Order is not waiting for payment';
    end if;

    update public.orders
    set status = 'AWAITING_COMPLIANCE'
    where id = p_order_id;

    insert into public.payments (
        order_id,
        checkout_session_id,
        payment_intent_id,
        status,
        amount_aud,
        fee_amount_aud
    )
    values (
        p_order_id,
        nullif(trim(p_checkout_session_id), ''),
        nullif(trim(p_payment_intent_id), ''),
        'PAID',
        v_order.amount_aud + v_order.fee_amount_aud,
        v_order.fee_amount_aud
    )
    on conflict (order_id) do update
    set
        checkout_session_id = coalesce(
            excluded.checkout_session_id,
            public.payments.checkout_session_id
        ),
        payment_intent_id = coalesce(
            excluded.payment_intent_id,
            public.payments.payment_intent_id
        ),
        status = 'PAID';

    perform public.write_audit_event(
        'PAYMENT_RECEIVED',
        'order',
        p_order_id,
        jsonb_build_object(
            'provider', 'stripe',
            'checkout_session_id', nullif(trim(p_checkout_session_id), ''),
            'payment_intent_id', nullif(trim(p_payment_intent_id), '')
        )
    );
end;
$$;

revoke all on function public.mark_order_paid(bigint, text, text) from public;
grant execute on function public.mark_order_paid(bigint, text, text) to service_role;

create function public.fail_unpaid_order(
    p_order_id bigint,
    p_payment_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_order public.orders%rowtype;
    v_status text;
begin
    v_status := upper(trim(p_payment_status));

    if v_status not in ('FAILED', 'EXPIRED') then
        raise exception 'Invalid payment status';
    end if;

    select * into v_order
    from public.orders
    where id = p_order_id
    for update;

    if not found then
        return;
    end if;

    if v_order.status <> 'AWAITING_PAYMENT' then
        return;
    end if;

    update public.orders
    set status = 'CANCELLED'
    where id = p_order_id;

    perform public.release_order_reservation(p_order_id);

    update public.payments
    set status = v_status
    where order_id = p_order_id
      and status = 'PENDING';

    perform public.write_audit_event(
        'PAYMENT_FAILED',
        'order',
        p_order_id,
        jsonb_build_object('status', v_status)
    );
end;
$$;

revoke all on function public.fail_unpaid_order(bigint, text) from public;
grant execute on function public.fail_unpaid_order(bigint, text) to service_role;

create or replace function public.insert_simulated_order(
    p_listing_id bigint,
    p_buyer_organisation_id bigint,
    p_unit_price_aud numeric
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_listing public.listings%rowtype;
    v_holding public.quota_holdings%rowtype;
    v_buyer_name text;
    v_available numeric;
    v_amount numeric;
    v_order_id bigint;
    v_status text;
    v_charges boolean;
begin
    select * into v_listing
    from public.listings
    where id = p_listing_id
    for update;

    if not found then
        raise exception 'Listing not found';
    end if;

    if v_listing.status <> 'PUBLISHED' then
        raise exception 'Listing is not available';
    end if;

    if p_buyer_organisation_id = v_listing.organisation_id then
        raise exception 'Buyer and seller must be different organisations';
    end if;

    if p_unit_price_aud is null or p_unit_price_aud <= 0 then
        raise exception 'Price must be greater than zero';
    end if;

    select legal_name into v_buyer_name
    from public.organisations
    where id = p_buyer_organisation_id;

    if v_buyer_name is null then
        raise exception 'Organisation not found';
    end if;

    select * into v_holding
    from public.quota_holdings
    where id = v_listing.holding_id
    for update;

    if not found then
        raise exception 'Holding not found';
    end if;

    v_available := v_holding.quantity - coalesce((
        select sum(r.quantity)
        from public.quota_reservations as r
        where r.holding_id = v_holding.id
          and r.status = 'ACTIVE'
    ), 0);

    if v_listing.quantity > v_available then
        raise exception 'Quota is no longer available';
    end if;

    v_amount := round(v_listing.quantity * p_unit_price_aud, 2);

    if v_amount is null or v_amount <= 0 then
        raise exception 'Order amount must be greater than zero';
    end if;

    select organisations.stripe_charges_enabled
    into v_charges
    from public.organisations as organisations
    where organisations.id = v_listing.organisation_id;

    v_status := case
        when coalesce(v_charges, false) then 'AWAITING_PAYMENT'
        else 'AWAITING_COMPLIANCE'
    end;

    insert into public.orders (
        listing_id,
        holding_id,
        seller_organisation_id,
        buyer_organisation_id,
        offering,
        quantity,
        unit_price_aud,
        amount_aud,
        status,
        seller_name,
        buyer_name,
        fishery_name,
        quota_type_name,
        measurement_kind,
        unit_label,
        created_by_email
    )
    values (
        v_listing.id,
        v_listing.holding_id,
        v_listing.organisation_id,
        p_buyer_organisation_id,
        v_listing.offering,
        v_listing.quantity,
        p_unit_price_aud,
        v_amount,
        v_status,
        v_listing.seller_name,
        v_buyer_name,
        v_listing.fishery_name,
        v_listing.quota_type_name,
        v_listing.measurement_kind,
        v_listing.unit_label,
        public.current_user_email()
    )
    returning id into v_order_id;

    insert into public.quota_reservations (
        order_id,
        listing_id,
        holding_id,
        quantity,
        status
    )
    values (
        v_order_id,
        v_listing.id,
        v_listing.holding_id,
        v_listing.quantity,
        'ACTIVE'
    );

    insert into public.transactions (
        order_id,
        status,
        amount_aud
    )
    values (
        v_order_id,
        'PENDING',
        v_amount
    );

    update public.listings
    set
        status = 'RESERVED',
        unit_price_aud = p_unit_price_aud
    where id = v_listing.id;

    perform public.write_audit_event(
        'ORDER_CREATED',
        'order',
        v_order_id,
        jsonb_build_object(
            'listing_id', v_listing.id,
            'quantity', v_listing.quantity,
            'status', v_status
        )
    );

    perform public.write_audit_event(
        'QUOTA_RESERVED',
        'order',
        v_order_id,
        jsonb_build_object(
            'holding_id', v_listing.holding_id,
            'quantity', v_listing.quantity
        )
    );

    return v_order_id;
end;
$$;

create or replace function public.cancel_order(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_order public.orders%rowtype;
begin
    select * into v_order
    from public.orders
    where id = p_order_id
    for update;

    if not found then
        raise exception 'Order not found';
    end if;

    if v_order.status not in ('AWAITING_COMPLIANCE', 'AWAITING_PAYMENT') then
        raise exception 'Order cannot be cancelled';
    end if;

    if not public.is_platform_admin()
       and public.user_organisation_role(v_order.buyer_organisation_id) is null then
        raise exception 'You cannot cancel this order';
    end if;

    update public.orders
    set status = 'CANCELLED'
    where id = p_order_id;

    perform public.release_order_reservation(p_order_id);

    update public.payments
    set status = 'EXPIRED'
    where order_id = p_order_id
      and status = 'PENDING';

    perform public.write_audit_event(
        'ORDER_CANCELLED',
        'order',
        p_order_id,
        '{}'::jsonb
    );
end;
$$;

notify pgrst, 'reload schema';
