-- Phase 1: organisations and organisation_users.
-- No marketplace, auth, or quota tables.

create function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.organisations (
    id bigint generated by default as identity primary key,
    legal_name text not null,
    trading_name text,
    abn text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint organisations_abn_unique unique (abn)
);

create trigger organisations_set_updated_at
before update on public.organisations
for each row
execute function public.set_updated_at();

create table public.organisation_users (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null references public.organisations (id) on delete restrict,
    email text not null,
    role text not null,
    created_at timestamptz not null default now(),
    constraint organisation_users_role_check
        check (role in ('OWNER', 'ADMIN', 'MEMBER')),
    constraint organisation_users_organisation_email_unique
        unique (organisation_id, email)
);

create index organisation_users_organisation_id_idx
    on public.organisation_users (organisation_id);

alter table public.organisations enable row level security;
alter table public.organisation_users enable row level security;
