-- Recorded agreement to the current terms version. Buy, bid, and list
-- are refused in the app until a row exists for that person and version.

create table public.terms_acceptances (
    id bigint generated by default as identity primary key,
    email text not null,
    terms_version text not null,
    accepted_at timestamptz not null default now(),
    constraint terms_acceptances_email_check check (email like '%@%'),
    constraint terms_acceptances_version_check check (char_length(terms_version) between 1 and 40),
    constraint terms_acceptances_email_version_key unique (email, terms_version)
);

create index terms_acceptances_email_idx
    on public.terms_acceptances (email);

alter table public.terms_acceptances enable row level security;

grant select on public.terms_acceptances to authenticated;

create policy terms_acceptances_select
on public.terms_acceptances
for select
to authenticated
using (email = public.current_user_email());

create function public.accept_terms(p_version text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_email text;
    v_version text;
begin
    v_email := public.current_user_email();
    v_version := lower(trim(coalesce(p_version, '')));

    if v_email is null or v_email = '' then
        raise exception 'Not authenticated';
    end if;

    if v_version = '' or char_length(v_version) > 40 then
        raise exception 'Terms version is required';
    end if;

    insert into public.terms_acceptances (email, terms_version)
    values (v_email, v_version)
    on conflict (email, terms_version) do nothing;
end;
$$;

revoke all on function public.accept_terms(text) from public;
grant execute on function public.accept_terms(text) to authenticated;

create or replace function public.sync_organisation_user_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_old text;
    v_new text;
begin
    if new.email is null
       or old.email is null
       or lower(new.email) is not distinct from lower(old.email) then
        return new;
    end if;

    v_old := lower(old.email);
    v_new := lower(new.email);

    update public.organisation_users
    set email = v_new
    where email = v_old;

    if not exists (
        select 1 from public.user_email_preferences where email = v_new
    ) then
        update public.user_email_preferences
        set email = v_new
        where email = v_old;
    else
        delete from public.user_email_preferences
        where email = v_old;
    end if;

    delete from public.listing_alerts as incoming
    using public.listing_alerts as existing
    where incoming.email = v_old
      and existing.email = v_new
      and incoming.fishery_id = existing.fishery_id;

    update public.listing_alerts
    set email = v_new
    where email = v_old;

    update public.user_notifications
    set email = v_new
    where email = v_old;

    delete from public.terms_acceptances as incoming
    using public.terms_acceptances as existing
    where incoming.email = v_old
      and existing.email = v_new
      and incoming.terms_version = existing.terms_version;

    update public.terms_acceptances
    set email = v_new
    where email = v_old;

    return new;
end;
$$;

notify pgrst, 'reload schema';
