-- Phase 5: fisheries reference data, holdings, and an immutable quota ledger.
-- Do not assume quota is measured in weight. Rules are data, not hard-coded law.

create table public.platform_admins (
    email text primary key,
    created_at timestamptz not null default now()
);

alter table public.platform_admins enable row level security;

create function public.is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.platform_admins as admins
        where admins.email = public.current_user_email()
    )
$$;

revoke all on function public.is_platform_admin() from public;
grant execute on function public.is_platform_admin() to authenticated;

create function public.platform_admin_count()
returns integer
language sql
stable
security definer
set search_path = public
as $$
    select count(*)::integer from public.platform_admins
$$;

revoke all on function public.platform_admin_count() from public;
grant execute on function public.platform_admin_count() to authenticated;

create function public.claim_first_platform_admin()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_email text;
begin
    v_email := public.current_user_email();

    if v_email is null or v_email = '' then
        raise exception 'Not authenticated';
    end if;

    if exists (select 1 from public.platform_admins) then
        raise exception 'A platform admin already exists';
    end if;

    insert into public.platform_admins (email) values (v_email);
end;
$$;

revoke all on function public.claim_first_platform_admin() from public;
grant execute on function public.claim_first_platform_admin() to authenticated;

create policy platform_admins_select
on public.platform_admins
for select
to authenticated
using (public.is_platform_admin());

create table public.jurisdictions (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    created_at timestamptz not null default now()
);

create table public.authorities (
    id bigint generated by default as identity primary key,
    jurisdiction_id bigint not null references public.jurisdictions (id) on delete restrict,
    name text not null,
    created_at timestamptz not null default now()
);

create table public.fisheries (
    id bigint generated by default as identity primary key,
    authority_id bigint not null references public.authorities (id) on delete restrict,
    name text not null,
    code text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger fisheries_set_updated_at
before update on public.fisheries
for each row
execute function public.set_updated_at();

create table public.species (
    id bigint generated by default as identity primary key,
    common_name text not null,
    scientific_name text,
    created_at timestamptz not null default now()
);

create table public.stocks (
    id bigint generated by default as identity primary key,
    fishery_id bigint not null references public.fisheries (id) on delete restrict,
    species_id bigint not null references public.species (id) on delete restrict,
    name text not null,
    created_at timestamptz not null default now(),
    constraint stocks_fishery_species_name_unique unique (fishery_id, species_id, name)
);

create table public.seasons (
    id bigint generated by default as identity primary key,
    fishery_id bigint not null references public.fisheries (id) on delete restrict,
    name text not null,
    starts_on date not null,
    ends_on date not null,
    created_at timestamptz not null default now(),
    constraint seasons_dates_check check (starts_on <= ends_on)
);

create table public.quota_types (
    id bigint generated by default as identity primary key,
    fishery_id bigint not null references public.fisheries (id) on delete restrict,
    measurement_kind text not null,
    name text not null,
    unit_label text not null,
    created_at timestamptz not null default now(),
    constraint quota_types_measurement_kind_check
        check (measurement_kind in ('WEIGHT', 'UNITS', 'EFFORT', 'OTHER')),
    constraint quota_types_fishery_name_unique unique (fishery_id, name)
);

create table public.fishery_rules (
    id bigint generated by default as identity primary key,
    fishery_id bigint not null references public.fisheries (id) on delete restrict,
    code text not null,
    value jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint fishery_rules_fishery_code_unique unique (fishery_id, code)
);

create table public.quota_holdings (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null references public.organisations (id) on delete restrict,
    stock_id bigint not null references public.stocks (id) on delete restrict,
    season_id bigint not null references public.seasons (id) on delete restrict,
    quota_type_id bigint not null references public.quota_types (id) on delete restrict,
    quantity numeric(18, 6) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint quota_holdings_quantity_check check (quantity >= 0),
    constraint quota_holdings_unique
        unique (organisation_id, stock_id, season_id, quota_type_id)
);

create trigger quota_holdings_set_updated_at
before update on public.quota_holdings
for each row
execute function public.set_updated_at();

create table public.quota_ledger (
    id bigint generated by default as identity primary key,
    holding_id bigint not null references public.quota_holdings (id) on delete restrict,
    event_type text not null,
    quantity_delta numeric(18, 6) not null,
    quantity_after numeric(18, 6) not null,
    note text,
    created_at timestamptz not null default now(),
    created_by_email text,
    constraint quota_ledger_event_type_check
        check (event_type in (
            'INITIAL_ALLOCATION',
            'PURCHASE',
            'SALE',
            'LEASE_IN',
            'LEASE_OUT',
            'TRANSFER',
            'RETURN',
            'ADJUSTMENT',
            'AUTHORITY_ADJUSTMENT',
            'REVERSAL'
        ))
);

create index quota_ledger_holding_id_idx on public.quota_ledger (holding_id);

create function public.prevent_quota_ledger_mutation()
returns trigger
language plpgsql
as $$
begin
    raise exception 'quota_ledger is immutable';
end;
$$;

create trigger quota_ledger_no_update
before update or delete on public.quota_ledger
for each row
execute function public.prevent_quota_ledger_mutation();

create function public.create_quota_holding(
    p_organisation_id bigint,
    p_stock_id bigint,
    p_season_id bigint,
    p_quota_type_id bigint,
    p_quantity numeric,
    p_note text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_holding_id bigint;
    v_fishery_id bigint;
    v_season_fishery_id bigint;
    v_type_fishery_id bigint;
begin
    if not public.is_platform_admin() then
        raise exception 'Not a platform admin';
    end if;

    if p_quantity is null or p_quantity <= 0 then
        raise exception 'Quantity must be greater than zero';
    end if;

    select fishery_id into v_fishery_id
    from public.stocks
    where id = p_stock_id;

    select fishery_id into v_season_fishery_id
    from public.seasons
    where id = p_season_id;

    select fishery_id into v_type_fishery_id
    from public.quota_types
    where id = p_quota_type_id;

    if v_fishery_id is null or v_season_fishery_id is null or v_type_fishery_id is null then
        raise exception 'Stock, season and quota type are required';
    end if;

    if v_fishery_id <> v_season_fishery_id or v_fishery_id <> v_type_fishery_id then
        raise exception 'Stock, season and quota type must belong to the same fishery';
    end if;

    insert into public.quota_holdings (
        organisation_id,
        stock_id,
        season_id,
        quota_type_id,
        quantity
    )
    values (
        p_organisation_id,
        p_stock_id,
        p_season_id,
        p_quota_type_id,
        p_quantity
    )
    returning id into v_holding_id;

    insert into public.quota_ledger (
        holding_id,
        event_type,
        quantity_delta,
        quantity_after,
        note,
        created_by_email
    )
    values (
        v_holding_id,
        'INITIAL_ALLOCATION',
        p_quantity,
        p_quantity,
        nullif(trim(p_note), ''),
        public.current_user_email()
    );

    return v_holding_id;
end;
$$;

revoke all on function public.create_quota_holding(bigint, bigint, bigint, bigint, numeric, text) from public;
grant execute on function public.create_quota_holding(bigint, bigint, bigint, bigint, numeric, text) to authenticated;

alter table public.jurisdictions enable row level security;
alter table public.authorities enable row level security;
alter table public.fisheries enable row level security;
alter table public.species enable row level security;
alter table public.stocks enable row level security;
alter table public.seasons enable row level security;
alter table public.quota_types enable row level security;
alter table public.fishery_rules enable row level security;
alter table public.quota_holdings enable row level security;
alter table public.quota_ledger enable row level security;

create policy jurisdictions_select on public.jurisdictions for select to authenticated using (true);
create policy authorities_select on public.authorities for select to authenticated using (true);
create policy fisheries_select on public.fisheries for select to authenticated using (true);
create policy species_select on public.species for select to authenticated using (true);
create policy stocks_select on public.stocks for select to authenticated using (true);
create policy seasons_select on public.seasons for select to authenticated using (true);
create policy quota_types_select on public.quota_types for select to authenticated using (true);
create policy fishery_rules_select on public.fishery_rules for select to authenticated using (true);

create policy jurisdictions_write on public.jurisdictions for all to authenticated
using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy authorities_write on public.authorities for all to authenticated
using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy fisheries_write on public.fisheries for all to authenticated
using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy species_write on public.species for all to authenticated
using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy stocks_write on public.stocks for all to authenticated
using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy seasons_write on public.seasons for all to authenticated
using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy quota_types_write on public.quota_types for all to authenticated
using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy fishery_rules_write on public.fishery_rules for all to authenticated
using (public.is_platform_admin()) with check (public.is_platform_admin());

create policy quota_holdings_select
on public.quota_holdings
for select
to authenticated
using (
    public.is_platform_admin()
    or public.user_organisation_role(organisation_id) is not null
);

create policy quota_ledger_select
on public.quota_ledger
for select
to authenticated
using (
    public.is_platform_admin()
    or exists (
        select 1
        from public.quota_holdings as holdings
        where holdings.id = quota_ledger.holding_id
          and public.user_organisation_role(holdings.organisation_id) is not null
    )
);

create policy organisations_admin_select
on public.organisations
for select
to authenticated
using (public.is_platform_admin());

insert into public.jurisdictions (code, name)
values
    ('CTH', 'Commonwealth of Australia'),
    ('NSW', 'New South Wales'),
    ('VIC', 'Victoria'),
    ('QLD', 'Queensland'),
    ('SA', 'South Australia'),
    ('WA', 'Western Australia'),
    ('TAS', 'Tasmania'),
    ('NT', 'Northern Territory'),
    ('ACT', 'Australian Capital Territory');
