-- Phase 10: Queensland transfer process.
-- Shared business fields, jurisdiction profiles, versioned form templates,
-- transfer applications/documents, and a private storage bucket.

alter table public.organisations
    add column if not exists entity_kind text,
    add column if not exists acn text,
    add column if not exists phone text,
    add column if not exists mobile text,
    add column if not exists registered_address text,
    add column if not exists postal_address text;

alter table public.organisations
    drop constraint if exists organisations_entity_kind_check;

alter table public.organisations
    add constraint organisations_entity_kind_check
        check (entity_kind is null or entity_kind in ('INDIVIDUAL', 'COMPANY'));

create unique index if not exists organisations_acn_unique
    on public.organisations (acn)
    where acn is not null;

create table if not exists public.organisation_jurisdiction_profiles (
    id bigint generated by default as identity primary key,
    organisation_id bigint not null references public.organisations (id) on delete restrict,
    jurisdiction_id bigint not null references public.jurisdictions (id) on delete restrict,
    client_reference text,
    licence_number text,
    fishery_symbols text,
    extra jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint organisation_jurisdiction_profiles_unique
        unique (organisation_id, jurisdiction_id)
);

create trigger organisation_jurisdiction_profiles_set_updated_at
before update on public.organisation_jurisdiction_profiles
for each row
execute function public.set_updated_at();

alter table public.organisation_jurisdiction_profiles enable row level security;

create policy organisation_jurisdiction_profiles_select
on public.organisation_jurisdiction_profiles
for select
to authenticated
using (
    public.is_platform_admin()
    or public.user_organisation_role(organisation_id) is not null
);

create policy organisation_jurisdiction_profiles_insert
on public.organisation_jurisdiction_profiles
for insert
to authenticated
with check (public.user_organisation_role(organisation_id) in ('OWNER', 'ADMIN'));

create policy organisation_jurisdiction_profiles_update
on public.organisation_jurisdiction_profiles
for update
to authenticated
using (public.user_organisation_role(organisation_id) in ('OWNER', 'ADMIN'))
with check (public.user_organisation_role(organisation_id) in ('OWNER', 'ADMIN'));

create table if not exists public.transfer_form_templates (
    id bigint generated by default as identity primary key,
    jurisdiction_id bigint references public.jurisdictions (id) on delete restrict,
    offering text not null,
    form_type text not null,
    form_version text not null,
    title text not null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    constraint transfer_form_templates_offering_check
        check (offering in ('SALE', 'LEASE')),
    constraint transfer_form_templates_unique
        unique (jurisdiction_id, offering, form_type, form_version)
);

alter table public.transfer_form_templates enable row level security;

create policy transfer_form_templates_select
on public.transfer_form_templates
for select
to authenticated
using (true);

insert into public.transfer_form_templates (
    jurisdiction_id,
    offering,
    form_type,
    form_version,
    title,
    active
)
select
    j.id,
    'SALE',
    'FDU1465',
    'V02/26',
    'Permanent transfer of quota and/or effort units (FDU1465)',
    true
from public.jurisdictions as j
where j.code = 'QLD'
on conflict (jurisdiction_id, offering, form_type, form_version) do nothing;

insert into public.transfer_form_templates (
    jurisdiction_id,
    offering,
    form_type,
    form_version,
    title,
    active
)
select
    j.id,
    'LEASE',
    'FDU_LEASE',
    'V01/26',
    'Queensland lease / temporary transfer application (official form code pending)',
    true
from public.jurisdictions as j
where j.code = 'QLD'
on conflict (jurisdiction_id, offering, form_type, form_version) do nothing;

create table if not exists public.transfer_applications (
    id bigint generated by default as identity primary key,
    order_id bigint not null unique references public.orders (id) on delete restrict,
    process_code text not null,
    form_type text,
    form_version text,
    status text not null default 'READY',
    fq_reference text,
    submission_method text,
    submitted_at timestamptz,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint transfer_applications_process_check
        check (process_code in ('QLD_SALE', 'QLD_LEASE', 'SIMULATED')),
    constraint transfer_applications_status_check
        check (status in (
            'READY',
            'DOCUMENT_GENERATED',
            'AWAITING_SIGNED_PACK',
            'ADMIN_REVIEW',
            'SUBMITTED',
            'PROCESSING',
            'APPROVED',
            'ACTION_REQUIRED'
        ))
);

create trigger transfer_applications_set_updated_at
before update on public.transfer_applications
for each row
execute function public.set_updated_at();

alter table public.transfer_applications enable row level security;

create policy transfer_applications_select
on public.transfer_applications
for select
to authenticated
using (
    public.is_platform_admin()
    or exists (
        select 1
        from public.orders as o
        where o.id = transfer_applications.order_id
          and (
              public.user_organisation_role(o.buyer_organisation_id) is not null
              or public.user_organisation_role(o.seller_organisation_id) is not null
          )
    )
);

create policy transfer_applications_insert
on public.transfer_applications
for insert
to authenticated
with check (
    public.is_platform_admin()
    or exists (
        select 1
        from public.orders as o
        where o.id = transfer_applications.order_id
          and o.status = 'AWAITING_TRANSFER'
          and (
              public.user_organisation_role(o.buyer_organisation_id) is not null
              or public.user_organisation_role(o.seller_organisation_id) is not null
          )
    )
);

create policy transfer_applications_admin_update
on public.transfer_applications
for update
to authenticated
using (public.is_platform_admin())
with check (public.is_platform_admin());

create table if not exists public.transfer_documents (
    id bigint generated by default as identity primary key,
    application_id bigint not null references public.transfer_applications (id) on delete restrict,
    document_type text not null,
    form_type text,
    form_version text,
    storage_path text not null,
    original_filename text,
    created_at timestamptz not null default now(),
    created_by_email text,
    constraint transfer_documents_type_check
        check (document_type in ('UNSIGNED_APPLICATION', 'SIGNED_PACK', 'SUPPORTING'))
);

create index if not exists transfer_documents_application_id_idx
    on public.transfer_documents (application_id);

alter table public.transfer_documents enable row level security;

create policy transfer_documents_select
on public.transfer_documents
for select
to authenticated
using (
    exists (
        select 1
        from public.transfer_applications as a
        join public.orders as o on o.id = a.order_id
        where a.id = transfer_documents.application_id
          and (
              public.is_platform_admin()
              or public.user_organisation_role(o.buyer_organisation_id) is not null
              or public.user_organisation_role(o.seller_organisation_id) is not null
          )
    )
);

create policy transfer_documents_insert
on public.transfer_documents
for insert
to authenticated
with check (
    exists (
        select 1
        from public.transfer_applications as a
        join public.orders as o on o.id = a.order_id
        where a.id = transfer_documents.application_id
          and (
              public.is_platform_admin()
              or public.user_organisation_role(o.buyer_organisation_id) is not null
              or public.user_organisation_role(o.seller_organisation_id) is not null
          )
    )
);

create function public.write_order_audit_event(
    p_order_id bigint,
    p_event_type text,
    p_payload jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_platform_admin()
       and not exists (
           select 1
           from public.orders as o
           where o.id = p_order_id
             and (
                 public.user_organisation_role(o.buyer_organisation_id) is not null
                 or public.user_organisation_role(o.seller_organisation_id) is not null
             )
       )
    then
        raise exception 'Not allowed';
    end if;

    perform public.write_audit_event(
        p_event_type,
        'order',
        p_order_id,
        coalesce(p_payload, '{}'::jsonb)
    );
end;
$$;

revoke all on function public.write_order_audit_event(bigint, text, jsonb) from public;
grant execute on function public.write_order_audit_event(bigint, text, jsonb) to authenticated;

create function public.transfer_party_profile_payload(p_organisation_id bigint, p_jurisdiction_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
    select jsonb_build_object(
        'id', o.id,
        'legal_name', o.legal_name,
        'trading_name', o.trading_name,
        'abn', o.abn,
        'entity_kind', o.entity_kind,
        'acn', o.acn,
        'phone', o.phone,
        'mobile', o.mobile,
        'registered_address', o.registered_address,
        'postal_address', o.postal_address,
        'signatories', (
            select coalesce(
                jsonb_agg(
                    jsonb_build_object(
                        'full_name', u.full_name,
                        'role', u.role
                    )
                    order by u.role, u.full_name
                ),
                '[]'::jsonb
            )
            from public.organisation_users as u
            where u.organisation_id = o.id
              and u.role in ('OWNER', 'ADMIN')
        ),
        'profile', (
            select jsonb_build_object(
                'organisation_id', p.organisation_id,
                'jurisdiction_id', p.jurisdiction_id,
                'client_reference', p.client_reference,
                'licence_number', p.licence_number,
                'fishery_symbols', p.fishery_symbols
            )
            from public.organisation_jurisdiction_profiles as p
            where p.organisation_id = o.id
              and p.jurisdiction_id = p_jurisdiction_id
        )
    )
    from public.organisations as o
    where o.id = p_organisation_id;
$$;

create function public.get_transfer_party_profiles(p_order_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v_order public.orders%rowtype;
    v_jurisdiction_id bigint;
begin
    select * into v_order
    from public.orders
    where id = p_order_id;

    if not found then
        return null;
    end if;

    if not public.is_platform_admin()
       and public.user_organisation_role(v_order.buyer_organisation_id) is null
       and public.user_organisation_role(v_order.seller_organisation_id) is null
    then
        raise exception 'Not allowed';
    end if;

    select f.jurisdiction_id into v_jurisdiction_id
    from public.quota_holdings as h
    join public.fisheries as f on f.id = h.fishery_id
    where h.id = v_order.holding_id;

    return jsonb_build_object(
        'jurisdiction_id', v_jurisdiction_id,
        'buyer', public.transfer_party_profile_payload(
            v_order.buyer_organisation_id,
            v_jurisdiction_id
        ),
        'seller', public.transfer_party_profile_payload(
            v_order.seller_organisation_id,
            v_jurisdiction_id
        )
    );
end;
$$;

revoke all on function public.transfer_party_profile_payload(bigint, bigint) from public;
revoke all on function public.get_transfer_party_profiles(bigint) from public;
grant execute on function public.get_transfer_party_profiles(bigint) to authenticated;

insert into storage.buckets (id, name, public)
values ('transfer-documents', 'transfer-documents', false)
on conflict (id) do nothing;

create or replace function public.transfer_document_order_id(p_name text)
returns bigint
language plpgsql
immutable
as $$
declare
    v_folder text;
begin
    v_folder := (storage.foldername(p_name))[1];
    if v_folder ~ '^\d+$' then
        return v_folder::bigint;
    end if;
    return null;
end;
$$;

drop policy if exists transfer_documents_storage_select on storage.objects;
create policy transfer_documents_storage_select
on storage.objects
for select
to authenticated
using (
    bucket_id = 'transfer-documents'
    and (
        public.is_platform_admin()
        or exists (
            select 1
            from public.orders as o
            where o.id = public.transfer_document_order_id(name)
              and (
                  public.user_organisation_role(o.buyer_organisation_id) is not null
                  or public.user_organisation_role(o.seller_organisation_id) is not null
              )
        )
    )
);

drop policy if exists transfer_documents_storage_insert on storage.objects;
create policy transfer_documents_storage_insert
on storage.objects
for insert
to authenticated
with check (
    bucket_id = 'transfer-documents'
    and (
        public.is_platform_admin()
        or exists (
            select 1
            from public.orders as o
            where o.id = public.transfer_document_order_id(name)
              and o.status = 'AWAITING_TRANSFER'
              and (
                  public.user_organisation_role(o.buyer_organisation_id) is not null
                  or public.user_organisation_role(o.seller_organisation_id) is not null
              )
        )
    )
);
