-- Phase 8: English auctions. Bid time is always server now(). No Stripe.

alter table public.listings
    drop constraint listings_type_check;

alter table public.listings
    add constraint listings_type_check
        check (listing_type in ('FIXED_PRICE', 'AUCTION'));

alter table public.listings
    drop constraint listings_status_check;

alter table public.listings
    add constraint listings_status_check
        check (status in (
            'PENDING_APPROVAL',
            'PUBLISHED',
            'RESERVED',
            'SOLD',
            'UNSOLD',
            'CANCELLED',
            'REJECTED'
        ));

alter table public.listings
    add column starting_price_aud numeric(18, 2),
    add column reserve_price_aud numeric(18, 2),
    add column bid_increment_aud numeric(18, 2),
    add column starts_at timestamptz;

alter table public.listings
    add constraint listings_auction_fields_check
        check (
            (
                listing_type = 'FIXED_PRICE'
                and starting_price_aud is null
                and reserve_price_aud is null
                and bid_increment_aud is null
                and starts_at is null
            )
            or (
                listing_type = 'AUCTION'
                and starting_price_aud is not null
                and starting_price_aud > 0
                and bid_increment_aud is not null
                and bid_increment_aud > 0
                and starts_at is not null
                and starts_at < expires_at
                and (reserve_price_aud is null or reserve_price_aud > 0)
            )
        );

drop policy listings_public_select on public.listings;

create policy listings_public_select
on public.listings
for select
to anon, authenticated
using (
    (status = 'PUBLISHED' and expires_at > now())
    or (
        listing_type = 'AUCTION'
        and status in ('PUBLISHED', 'RESERVED', 'SOLD', 'UNSOLD')
    )
);

create table public.bids (
    id bigint generated by default as identity primary key,
    listing_id bigint not null references public.listings (id) on delete restrict,
    organisation_id bigint not null references public.organisations (id) on delete restrict,
    bidder_name text not null,
    amount_aud numeric(18, 2) not null,
    created_at timestamptz not null default now(),
    constraint bids_amount_check check (amount_aud > 0)
);

create index bids_listing_id_idx on public.bids (listing_id);
create index bids_listing_amount_created_idx
    on public.bids (listing_id, amount_aud desc, created_at asc);

alter table public.bids enable row level security;

grant select on public.bids to anon, authenticated;

create policy bids_select
on public.bids
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.listings as l
        where l.id = bids.listing_id
          and (
              (
                  l.listing_type = 'AUCTION'
                  and l.status in ('PUBLISHED', 'RESERVED', 'SOLD', 'UNSOLD')
              )
              or public.user_organisation_role(l.organisation_id) is not null
              or public.user_organisation_role(bids.organisation_id) is not null
              or public.is_platform_admin()
          )
    )
);

create function public.insert_simulated_order(
    p_listing_id bigint,
    p_buyer_organisation_id bigint,
    p_unit_price_aud numeric
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_listing public.listings%rowtype;
    v_holding public.quota_holdings%rowtype;
    v_buyer_name text;
    v_available numeric;
    v_amount numeric;
    v_order_id bigint;
begin
    select * into v_listing
    from public.listings
    where id = p_listing_id
    for update;

    if not found then
        raise exception 'Listing not found';
    end if;

    if v_listing.status <> 'PUBLISHED' then
        raise exception 'Listing is not available';
    end if;

    if p_buyer_organisation_id = v_listing.organisation_id then
        raise exception 'Buyer and seller must be different organisations';
    end if;

    if p_unit_price_aud is null or p_unit_price_aud <= 0 then
        raise exception 'Price must be greater than zero';
    end if;

    select legal_name into v_buyer_name
    from public.organisations
    where id = p_buyer_organisation_id;

    if v_buyer_name is null then
        raise exception 'Organisation not found';
    end if;

    select * into v_holding
    from public.quota_holdings
    where id = v_listing.holding_id
    for update;

    if not found then
        raise exception 'Holding not found';
    end if;

    v_available := v_holding.quantity - coalesce((
        select sum(r.quantity)
        from public.quota_reservations as r
        where r.holding_id = v_holding.id
          and r.status = 'ACTIVE'
    ), 0);

    if v_listing.quantity > v_available then
        raise exception 'Quota is no longer available';
    end if;

    v_amount := round(v_listing.quantity * p_unit_price_aud, 2);

    if v_amount is null or v_amount <= 0 then
        raise exception 'Order amount must be greater than zero';
    end if;

    insert into public.orders (
        listing_id,
        holding_id,
        seller_organisation_id,
        buyer_organisation_id,
        offering,
        quantity,
        unit_price_aud,
        amount_aud,
        status,
        seller_name,
        buyer_name,
        fishery_name,
        stock_name,
        season_name,
        quota_type_name,
        measurement_kind,
        unit_label,
        created_by_email
    )
    values (
        v_listing.id,
        v_listing.holding_id,
        v_listing.organisation_id,
        p_buyer_organisation_id,
        v_listing.offering,
        v_listing.quantity,
        p_unit_price_aud,
        v_amount,
        'AWAITING_COMPLIANCE',
        v_listing.seller_name,
        v_buyer_name,
        v_listing.fishery_name,
        v_listing.stock_name,
        v_listing.season_name,
        v_listing.quota_type_name,
        v_listing.measurement_kind,
        v_listing.unit_label,
        public.current_user_email()
    )
    returning id into v_order_id;

    insert into public.quota_reservations (
        order_id,
        listing_id,
        holding_id,
        quantity,
        status
    )
    values (
        v_order_id,
        v_listing.id,
        v_listing.holding_id,
        v_listing.quantity,
        'ACTIVE'
    );

    insert into public.transactions (
        order_id,
        status,
        amount_aud
    )
    values (
        v_order_id,
        'PENDING',
        v_amount
    );

    update public.listings
    set
        status = 'RESERVED',
        unit_price_aud = p_unit_price_aud
    where id = v_listing.id;

    perform public.write_audit_event(
        'ORDER_CREATED',
        'order',
        v_order_id,
        jsonb_build_object(
            'listing_id', v_listing.id,
            'quantity', v_listing.quantity
        )
    );

    perform public.write_audit_event(
        'QUOTA_RESERVED',
        'order',
        v_order_id,
        jsonb_build_object(
            'holding_id', v_listing.holding_id,
            'quantity', v_listing.quantity
        )
    );

    return v_order_id;
end;
$$;

revoke all on function public.insert_simulated_order(bigint, bigint, numeric) from public;

create or replace function public.create_order(
    p_listing_id bigint,
    p_buyer_organisation_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_listing public.listings%rowtype;
begin
    if public.current_user_email() is null then
        raise exception 'Not authenticated';
    end if;

    if public.user_organisation_role(p_buyer_organisation_id) is null then
        raise exception 'You are not a member of that organisation';
    end if;

    select * into v_listing
    from public.listings
    where id = p_listing_id
    for update;

    if not found then
        raise exception 'Listing not found';
    end if;

    if v_listing.listing_type <> 'FIXED_PRICE' then
        raise exception 'This listing is an auction';
    end if;

    if v_listing.status <> 'PUBLISHED' or v_listing.expires_at <= now() then
        raise exception 'Listing is not available to purchase';
    end if;

    return public.insert_simulated_order(
        p_listing_id,
        p_buyer_organisation_id,
        v_listing.unit_price_aud
    );
end;
$$;

create or replace function public.cancel_listing(p_listing_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_org bigint;
    v_status text;
    v_type text;
    v_role text;
    v_bid_count integer;
begin
    select organisation_id, status, listing_type
    into v_org, v_status, v_type
    from public.listings
    where id = p_listing_id
    for update;

    if not found then
        raise exception 'Listing not found';
    end if;

    if v_status not in ('PENDING_APPROVAL', 'PUBLISHED') then
        raise exception 'Listing cannot be cancelled';
    end if;

    v_role := public.user_organisation_role(v_org);

    if not public.is_platform_admin()
       and (v_role is null or v_role not in ('OWNER', 'ADMIN')) then
        raise exception 'You cannot cancel this listing';
    end if;

    if v_type = 'AUCTION' then
        select count(*) into v_bid_count
        from public.bids
        where listing_id = p_listing_id;

        if v_bid_count > 0 and not public.is_platform_admin() then
            raise exception 'An auction with bids can only be cancelled by an admin';
        end if;
    end if;

    update public.listings
    set status = 'CANCELLED'
    where id = p_listing_id;
end;
$$;

create function public.create_auction(
    p_holding_id bigint,
    p_offering text,
    p_quantity numeric,
    p_starting_price_aud numeric,
    p_bid_increment_aud numeric,
    p_reserve_price_aud numeric,
    p_starts_at timestamptz,
    p_ends_at timestamptz
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_holding public.quota_holdings%rowtype;
    v_role text;
    v_id bigint;
    v_seller text;
    v_fishery text;
    v_stock text;
    v_season text;
    v_quota_type text;
    v_kind text;
    v_unit text;
    v_committed numeric;
    v_starts timestamptz;
begin
    if public.current_user_email() is null then
        raise exception 'Not authenticated';
    end if;

    select * into v_holding
    from public.quota_holdings
    where id = p_holding_id
    for update;

    if not found then
        raise exception 'Holding not found';
    end if;

    v_role := public.user_organisation_role(v_holding.organisation_id);

    if v_role is null or v_role not in ('OWNER', 'ADMIN') then
        raise exception 'You cannot auction quota for this organisation';
    end if;

    if p_offering not in ('SALE', 'LEASE') then
        raise exception 'Offering must be SALE or LEASE';
    end if;

    if p_quantity is null or p_quantity <= 0 then
        raise exception 'Quantity must be greater than zero';
    end if;

    v_committed := coalesce((
        select sum(r.quantity)
        from public.quota_reservations as r
        where r.holding_id = p_holding_id
          and r.status = 'ACTIVE'
    ), 0) + coalesce((
        select sum(l.quantity)
        from public.listings as l
        where l.holding_id = p_holding_id
          and l.status in ('PENDING_APPROVAL', 'PUBLISHED')
    ), 0);

    if p_quantity > v_holding.quantity - v_committed then
        raise exception 'Quantity cannot exceed the available holding';
    end if;

    if p_starting_price_aud is null or p_starting_price_aud <= 0 then
        raise exception 'Starting price must be greater than zero';
    end if;

    if p_bid_increment_aud is null or p_bid_increment_aud <= 0 then
        raise exception 'Bid increment must be greater than zero';
    end if;

    if p_reserve_price_aud is not null and p_reserve_price_aud <= 0 then
        raise exception 'Reserve price must be greater than zero';
    end if;

    v_starts := coalesce(p_starts_at, now());

    if p_ends_at is null or p_ends_at <= now() then
        raise exception 'Auction end must be in the future';
    end if;

    if v_starts >= p_ends_at then
        raise exception 'Auction start must be before the end';
    end if;

    select o.legal_name into v_seller
    from public.organisations as o
    where o.id = v_holding.organisation_id;

    select f.name, st.name, se.name, qt.name, qt.measurement_kind, qt.unit_label
    into v_fishery, v_stock, v_season, v_quota_type, v_kind, v_unit
    from public.stocks as st
    join public.fisheries as f on f.id = st.fishery_id
    join public.seasons as se on se.id = v_holding.season_id
    join public.quota_types as qt on qt.id = v_holding.quota_type_id
    where st.id = v_holding.stock_id;

    insert into public.listings (
        organisation_id,
        holding_id,
        listing_type,
        offering,
        quantity,
        unit_price_aud,
        expires_at,
        status,
        seller_name,
        fishery_name,
        stock_name,
        season_name,
        quota_type_name,
        measurement_kind,
        unit_label,
        created_by_email,
        starting_price_aud,
        reserve_price_aud,
        bid_increment_aud,
        starts_at
    )
    values (
        v_holding.organisation_id,
        p_holding_id,
        'AUCTION',
        p_offering,
        p_quantity,
        p_starting_price_aud,
        p_ends_at,
        'PENDING_APPROVAL',
        v_seller,
        v_fishery,
        v_stock,
        v_season,
        v_quota_type,
        v_kind,
        v_unit,
        public.current_user_email(),
        p_starting_price_aud,
        p_reserve_price_aud,
        p_bid_increment_aud,
        v_starts
    )
    returning id into v_id;

    return v_id;
end;
$$;

revoke all on function public.create_auction(bigint, text, numeric, numeric, numeric, numeric, timestamptz, timestamptz) from public;
grant execute on function public.create_auction(bigint, text, numeric, numeric, numeric, numeric, timestamptz, timestamptz) to authenticated;

create function public.place_bid(
    p_listing_id bigint,
    p_bidder_organisation_id bigint,
    p_amount_aud numeric
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_listing public.listings%rowtype;
    v_bidder_name text;
    v_min numeric;
    v_bid_id bigint;
    v_now timestamptz;
begin
    v_now := now();

    if public.current_user_email() is null then
        raise exception 'Not authenticated';
    end if;

    if public.user_organisation_role(p_bidder_organisation_id) is null then
        raise exception 'You are not a member of that organisation';
    end if;

    select * into v_listing
    from public.listings
    where id = p_listing_id
    for update;

    if not found then
        raise exception 'Auction not found';
    end if;

    if v_listing.listing_type <> 'AUCTION' then
        raise exception 'This listing is not an auction';
    end if;

    if v_listing.status <> 'PUBLISHED' then
        raise exception 'Auction is not open for bids';
    end if;

    if v_listing.expires_at <= v_now then
        raise exception 'Auction has ended';
    end if;

    if v_listing.starts_at > v_now then
        raise exception 'Auction has not started';
    end if;

    if p_bidder_organisation_id = v_listing.organisation_id then
        raise exception 'You cannot bid on your organisation''s auction';
    end if;

    if p_amount_aud is null or p_amount_aud <= 0 then
        raise exception 'Bid must be greater than zero';
    end if;

    if exists (select 1 from public.bids where listing_id = p_listing_id) then
        v_min := v_listing.unit_price_aud + v_listing.bid_increment_aud;
    else
        v_min := v_listing.starting_price_aud;
    end if;

    if p_amount_aud < v_min then
        raise exception 'Bid must be at least %', v_min;
    end if;

    select legal_name into v_bidder_name
    from public.organisations
    where id = p_bidder_organisation_id;

    insert into public.bids (
        listing_id,
        organisation_id,
        bidder_name,
        amount_aud
    )
    values (
        p_listing_id,
        p_bidder_organisation_id,
        v_bidder_name,
        p_amount_aud
    )
    returning id into v_bid_id;

    update public.listings
    set unit_price_aud = p_amount_aud
    where id = p_listing_id;

    perform public.write_audit_event(
        'BID_PLACED',
        'listing',
        p_listing_id,
        jsonb_build_object(
            'bid_id', v_bid_id,
            'organisation_id', p_bidder_organisation_id,
            'amount_aud', p_amount_aud
        )
    );

    return v_bid_id;
end;
$$;

revoke all on function public.place_bid(bigint, bigint, numeric) from public;
grant execute on function public.place_bid(bigint, bigint, numeric) to authenticated;

create function public.close_auction(p_listing_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_listing public.listings%rowtype;
    v_bid public.bids%rowtype;
    v_order_id bigint;
begin
    if public.current_user_email() is null then
        raise exception 'Not authenticated';
    end if;

    select * into v_listing
    from public.listings
    where id = p_listing_id
    for update;

    if not found then
        raise exception 'Auction not found';
    end if;

    if v_listing.listing_type <> 'AUCTION' then
        raise exception 'This listing is not an auction';
    end if;

    if v_listing.status in ('RESERVED', 'SOLD', 'UNSOLD', 'CANCELLED', 'REJECTED') then
        return null;
    end if;

    if v_listing.status <> 'PUBLISHED' then
        raise exception 'Auction cannot be closed';
    end if;

    if v_listing.expires_at > now() then
        raise exception 'Auction has not ended';
    end if;

    select * into v_bid
    from public.bids
    where listing_id = p_listing_id
    order by amount_aud desc, created_at asc
    limit 1;

    if not found
       or (
           v_listing.reserve_price_aud is not null
           and v_bid.amount_aud < v_listing.reserve_price_aud
       ) then
        update public.listings
        set status = 'UNSOLD'
        where id = p_listing_id;

        perform public.write_audit_event(
            'AUCTION_UNSOLD',
            'listing',
            p_listing_id,
            jsonb_build_object(
                'high_bid', v_bid.amount_aud
            )
        );

        return null;
    end if;

    v_order_id := public.insert_simulated_order(
        p_listing_id,
        v_bid.organisation_id,
        v_bid.amount_aud
    );

    perform public.write_audit_event(
        'AUCTION_CLOSED',
        'listing',
        p_listing_id,
        jsonb_build_object(
            'order_id', v_order_id,
            'bid_id', v_bid.id,
            'amount_aud', v_bid.amount_aud
        )
    );

    return v_order_id;
end;
$$;

revoke all on function public.close_auction(bigint) from public;
grant execute on function public.close_auction(bigint) to authenticated;
